import React from 'react';

import {Grid} from 'react-uikit3';
import {CopyToClipboard} from 'react-copy-to-clipboard';

export default class Sign extends React.Component {
  constructor(props) {

    super(props)

    this.state = {
      signerAccount: '',
      appName: 'ABCompany',
      account: 'GC2BKLYOOYPDEFJKLKY6FNNRQMGFLVHJKQRGNSSRRGSMPGF32LHCQVGF',
      trustAmount: 10000,
      tokenCode: 'ABCD',
      logoUrl: 'http://lorempixel.com/800/300',
      message: 'Nullam quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.'
    }

    this.handleChange = this.handleChange.bind(this)

    var data = atob(this.props.match.params.id);
    console.log(data);

  }

  handleChange(event) {
    this.setState({ [event.target.name]: event.target.value })
  }

  render() {
    return (
      <Grid className="uk-child-width-1-2@m uk-flex-center uk-padding">
        <div className='container uk-padding uk-light'>
          <p className="uk-text-right">Token Trust Form generated by &nbsp;<a href="#"><strong>{this.state.appName}</strong></a> | <a className="text-primary">Create yours</a></p>

          <h2><span className="uk-badge uk-padding-small network-badge">{this.state.testnet ? 'Testnet' : 'Public Net'}</span> Trust new token <strong>ABCD</strong></h2>

          <form onChange={this.handleChange} onSubmit={this.submit} method="POST">
            <fieldset className="uk-fieldset">

              <h3>Overview</h3>

              <img src={this.state.logoUrl} />

              <div className="uk-margin uk-margin-bottom-large">
                <p>{this.state.message}</p>
              </div>

              <h3>Token Information</h3>

              <Grid className="uk-grid-divider uk-child-width-expand@s uk-margin-bottom">
                <div className="uk-text-right">
                  <label>Token ({(this.state.tokenType=='ALPHA12' ? 'Alpha 12' : 'Alpha 4')})</label>
                  <h3 className="uk-margin-remove"><strong>{this.state.tokenCode}</strong></h3>
                </div>
                <div>
                  <label>Trust Limit</label>
                  <h3 className="uk-margin-remove"><strong>{this.state.trustAmount} {this.state.tokenCode}</strong></h3>
                </div>
              </Grid>

              <hr/>

              <div className="uk-margin-bottom uk-text-center">
                <label>Issuing Account</label>
                <br/>
                <span className="code uk-margin-top uk-width-1-1">{this.state.stellarAccount}</span>
              </div>

              {/* <div className="uk-margin">

                <input className="uk-input uk-width-1-1" type="text" placeholder="Token Code" name="tokenCode" value={this.state.tokenCode} />
              <Grid className="uk-grid-small uk-margin-bottom">
                <div className="uk-width-1-3">

                </div>
                <div className="uk-width-2-3">

                </div>
              </Grid> */}

              <h3>Paste Your <u>Private Key</u></h3>

              <div className="uk-margin-bottom">
                  <input className="uk-input code" type="text" placeholder="GC2BKL..." name="signerAccount" value={this.state.signerAccount} />
              </div>

              <h5><strong>Security Information:</strong> <em>We never store your Private Key - anywhere. It is used in your browser to sign the transaction with the <a href="http://" className="text-primary">Stellar-JS-SDK</a>. Verify code of the sign component <a className="text-primary">here</a>.</em>
              </h5>

              <div className="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                 <label><input className="uk-checkbox uk-margin-small-right" type="checkbox" /> I agree to the terms & conditions.</label>
             </div>

             <div className="uk-margin-bottom">
               <button className="uk-button uk-button-primary uk-button-large uk-width-1-1"><b>Assign Trust</b></button>
             </div>

            </fieldset>
          </form>
        </div>
      </Grid>
    )
  }

}
